name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: Xanthus58.ValorantRandomizer
          installers-regex: '\.exe$'
          delete-previous-version: 'true'
          token: ${{ secrets.WINGET_TOKEN }} 
